jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: ${{ github.event.repository.name }}
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        cache: maven
        cache-dependency-path: docker/example-server/resources/server/pom.xml
        distribution: temurin
        java-version: 8
    - continue-on-error: true
      name: Build with Maven
      run: cd docker/example-server/resources/server && mvn -B package --file pom.xml
name: example server
on:
  repository_dispatch:
    types: trigger-ga___example-server.yml
