jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: ${{ github.event.repository.name }}
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        cache: maven
        cache-dependency-path: pom.xml
        distribution: temurin
        java-version: 8
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B package --file pom.xml
    - continue-on-error: true
      name: Archive generated JAR file
      uses: actions/upload-artifact@v4
      with:
        name: rmg-compiled-jars
        path: target/*.jar
name: maven CI
on:
  repository_dispatch:
    types: trigger-ga___maven-ci.yml
